from typing import Any, Tuple

def initialize() -> bool: ...
def shutdown() -> None: ...
def account_info() -> Any: ...
def symbol_info(symbol: str) -> Any: ...
def symbol_select(symbol: str) -> bool: ...
def last_error() -> Tuple[int, str]: ...
def version() -> Tuple[int, int, int]: ...

# Commonly referenced constants/types (kept as Any to satisfy the checker)
TIMEFRAME_M1: Any
TIMEFRAME_M5: Any
TIMEFRAME_M15: Any
TIMEFRAME_M30: Any
TIMEFRAME_H1: Any
TIMEFRAME_H4: Any
TIMEFRAME_H8: Any
TIMEFRAME_D1: Any
